import assert from 'node:assert/strict'
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const srcRoot = resolve(here, '..')
const read = (path: string) => readFileSync(resolve(here, path), 'utf8')

function sourceFiles(directory: string): string[] {
  return readdirSync(directory).flatMap((name) => {
    const path = join(directory, name)
    return statSync(path).isDirectory() ? sourceFiles(path) : /\.(?:ts|tsx)$/.test(name) ? [path] : []
  })
}

test('chat is a single assistant-ui external-store runtime', () => {
  const runtime = read('../features/chat/runtime/runtime.tsx')
  const model = read('../features/chat/runtime/model.ts')
  const thread = read('../features/chat/components/ConversationThread.tsx')
  const activity = read('../features/chat/components/ConversationActivity.tsx')
  const agentStatus = read('../components/assistant-ui/elements/agent-status.tsx')
  const composer = read('../features/chat/components/ConversationComposer.tsx')
  const lexicalInput = read('../features/chat/components/ComposerLexicalInput.tsx')
  const triggers = read('../features/chat/components/ComposerTriggers.tsx')
  const message = read('../features/chat/components/ConversationMessage.tsx')
  const markdown = read('../components/assistant-ui/markdown-text.tsx')
  const confidence = read('../components/assistant-ui/elements/confidence-marker.tsx')
  const documentReference = read('../components/assistant-ui/elements/document-reference.tsx')
  const elicitation = read('../components/assistant-ui/elements/elicitation-form.tsx')
  const agentPlan = read('../components/assistant-ui/elements/agent-plan.tsx')
  const handoff = read('../components/assistant-ui/elements/agent-handoff.tsx')
  const typingIndicator = read('../components/typing-indicator.tsx')
  const tools = read('../features/chat/components/ToolRenderers.tsx')
  const toolTimeline = read('../components/assistant-ui/elements/tool-timeline.tsx')
  const artifactCard = read('../components/assistant-ui/elements/artifact-card.tsx')
  const surfaces = read('../components/assistant-ui/elements/surfaces.tsx')
  const generativeStyles = read('../styles/generative-ui-elements.css')
  const statsDisplay = read('../components/tool-ui/stats-display/stats-display.tsx')
  const sparkline = read('../components/tool-ui/stats-display/sparkline.tsx')
  assert.match(runtime, /useExternalStoreRuntime<ThreadMessage>/)
  assert.match(model, /schema: 'lingxiloop\.thread-message\.v1'/)
  assert.match(model, /presentation: LingxiMessagePresentation/)
  for (const primitive of ['Root', 'Viewport', 'Messages', 'ScrollToBottom']) {
    assert.match(thread, new RegExp(`ThreadPrimitive\\.${primitive}`))
  }
  for (const primitive of ['Root', 'Attachments', 'AddAttachment', 'Quote', 'Send', 'Cancel']) {
    assert.match(composer, new RegExp(`ComposerPrimitive\\.${primitive}`))
  }
  assert.match(composer, /ComposerLexicalInput/)
  assert.match(lexicalInput, /LexicalComposerInput/)
  assert.match(lexicalInput, /directiveChip=\{ComposerDirectiveChip\}/)
  assert.match(triggers, /ComposerPrimitive\.Unstable_TriggerPopover/)
  assert.match(triggers, /unstable_useMentionAdapter/)
  assert.match(triggers, /unstable_useSlashCommandAdapter/)
  assert.match(triggers, /<Avatar p=\{participant\}/)
  assert.match(triggers, /UsersRoundIcon/)
  assert.match(triggers, /BarChart3Icon/)
  assert.match(message, /MessagePrimitive\.Root/)
  assert.match(message, /MessagePrimitive\.Parts/)
  assert.match(markdown, /className=\{segmented \? 'im-bubble-markdown im-bubble-markdown-agent'/)
  assert.doesNotMatch(markdown, /parseMarkdownIntoBlocksFn|splitMessageLines/)
  assert.doesNotMatch(markdown, /\btypeset\b|from 'streamdown'/)
  assert.match(message, /showMessageChrome && custom\.groupEnd/)
  assert.match(message, /isSpecialCard = custom\.presentation === 'special-card'/)
  assert.match(message, /showInheritedChrome = isSpecialCard && custom\.groupStart && custom\.clusterChromeAt !== null/)
  assert.match(message, /data-message-presentation=\{custom\.presentation\}/)
  assert.match(message, /special-card\]\+\[data-message-presentation=conversation\]\[data-message-continued-from=true\]\]:mt-1/)
  assert.match(message, /continuedFromPrevious \? isSpecialCard \? 'pt-1'/)
  assert.match(message, /grid w-full min-w-0 gap-0\.5/)
  assert.doesNotMatch(message, /message-attachments" className="[^"]*pb-1/)
  assert.match(message, /showMessageChrome && custom\.groupStart && !custom\.isMine/)
  assert.match(message, /<span className="font-medium">\{custom\.senderName\}<\/span>[\s\S]*<time>/)
  assert.match(message, /<TypingIndicator variant="bare"/)
  assert.match(message, /confidenceClaims=\{confidenceClaims\}/)
  assert.match(message, /toolName === 'cite_claims'/)
  assert.match(confidence, /data-slot="confidence-marker"/)
  assert.match(confidence, /grounded: "decoration-emerald-500\/50"/)
  assert.match(confidence, /export function ConfidenceMarkerInline/)
  assert.match(confidence, /group-hover\/confidence:visible/)
  assert.doesNotMatch(confidence, /Popover|variant = "inline"/)
  assert.match(markdown, /StreamdownTextPrimitive/)
  assert.match(markdown, /components=\{components\}/)
  assert.match(markdown, /<ConfidenceMarkerInline claim=\{claim\}>/)
  assert.doesNotMatch(markdown, /CitationLink|hoveredId|scrollIntoView/)
  assert.doesNotMatch(markdown, /openCitation|useKnowledgeSources/)
  assert.doesNotMatch(markdown, /annotateConfidenceMarkdown|preprocess=|allowedTags=|【S/)
  assert.doesNotMatch(markdown, /caret=/)
  assert.doesNotMatch(markdown, /\banimated\b/)
  assert.doesNotMatch(markdown, /\bsmooth\b|\bdefer\b/)
  assert.match(read('../styles/chat.css'), /\.im-bubble-markdown-agent \{ align-items: flex-start;/)
  assert.match(typingIndicator, /data-slot="typing-indicator"/)
  assert.doesNotMatch(thread, /AgentTypingIndicator/)
  assert.match(thread, /<ConversationActivity conversationId=\{conversationId\}/)
  assert.doesNotMatch(thread, /absolute inset-0/)
  assert.match(activity, /<AgentStatus/)
  assert.match(activity, /justify-center[^"]*" data-chat-agent-status/)
  assert.match(activity, /state=\{active\.runStatus === 'waiting_for_human' \? 'waiting' : 'working'\}/)
  assert.match(activity, /label=\{`\$\{active\.agentName\} · \$\{active\.title\}`\}/)
  assert.doesNotMatch(activity, /visible\.map|rounded-full|bg-muted/)
  assert.match(agentStatus, /data-slot="agent-status"/)
  assert.match(message, /ActionBarPrimitive\.Root/)
  assert.match(message, /ActionBarPrimitive\.Root className=\{cn\([\s\S]*bg-transparent[\s\S]*metadata\.isMine \? 'end-full me-2' : 'start-full ms-2'/)
  assert.match(message, /<ArtifactCard/)
  assert.match(message, /title=\{attachment\.filename\}/)
  assert.doesNotMatch(message, /@\/components\/ui\/attachment/)
  assert.doesNotMatch(tools, /tool-fallback/)
  assert.match(tools, /@\/components\/tool-ui\/stats-display/)
  assert.match(tools, /ipython: \(\) => null/)
  assert.match(tools, /cite_claims: \(\) => null/)
  assert.match(tools, /read_document: \(\) => null/)
  assert.doesNotMatch(tools, /<DocumentReference|ReadDocumentTool/)
  assert.match(documentReference, /data-slot="document-reference"/)
  assert.match(tools, /<RecommendationCard/)
  assert.match(tools, /respondToApproval\(\{ approved: true \}\)/)
  assert.match(tools, /<StatsDisplay/)
  assert.match(tools, /showStats: TeacherBriefingStatsTool/)
  assert.match(statsDisplay, /data-slot="stats-display"/)
  assert.match(statsDisplay, /<Sparkline/)
  assert.match(sparkline, /stroke=\{color\}/)
  assert.match(tools, /<ScoreBreakdown/)
  assert.match(tools, /'learning\.propose_evaluation': ScoreBreakdownTool/)
  assert.doesNotMatch(message, /custom\.citations|citationClaims/)
  assert.doesNotMatch(tools, /<ToolCall/)
  assert.match(tools, /<ToolTimeline/)
  assert.match(message, /<HostToolTimeline/)
  assert.equal(existsSync(resolve(here, '../components/tool-call.tsx')), false)
  assert.match(toolTimeline, /data-slot="tool-timeline"/)
  assert.match(tools, /calls\.length < 2 \|\| ownerId !== messageId/)
  assert.doesNotMatch(tools, /IPythonTool|label: 'IPython'/)
  assert.match(tools, /<ElicitationForm/)
  assert.match(tools, /'canvas-artifact': CanvasArtifactTool/)
  assert.match(tools, /<ArtifactCard/)
  assert.match(tools, /<AgentPlan/)
  assert.match(tools, /<AgentHandoff/)
  assert.match(tools, /draftEmailSpec/)
  assert.match(elicitation, /data-slot="elicitation-form"/)
  assert.match(agentPlan, /data-slot="agent-plan"/)
  assert.match(agentPlan, /cn\(paper, conversationCardSize\.standard/)
  assert.match(handoff, /data-slot="agent-handoff"/)
  assert.match(handoff, /fromAvatar/)
  assert.doesNotMatch(handoff, /reason|carried|随交接传递/)
  assert.match(tools, /fromAvatar=\{<Avatar p=\{from\}/)
  assert.match(tools, /<CardSurface data-aui-theme="elements"/)
  assert.match(artifactCard, /data-slot="artifact-card"/)
  assert.match(surfaces, /export const conversationCardSize = \{[\s\S]*tile:[\s\S]*compact:[\s\S]*standard:[\s\S]*wide:[\s\S]*inline:/)
  assert.match(surfaces, /paper = "bg-background border border-border\/60 dark:bg-popover"/)
  assert.match(surfaces, /field = "bg-foreground\/\[0\.04\] dark:bg-foreground\/\[0\.06\]"/)
  assert.doesNotMatch(surfaces, /@\/components\/ui\/card|<Card/)
  assert.match(surfaces, /bg-primary text-primary-foreground/)
  assert.match(generativeStyles, /background-color: var\(--background\)/)
  assert.match(generativeStyles, /background-color: var\(--popover\)/)
  assert.match(generativeStyles, /box-shadow: none/)
  assert.match(generativeStyles, /background-color: var\(--primary\)/)
  assert.match(tools, /conversationCardSize\.wide/)
  assert.match(tools, /conversationCardSize\.standard/)
  assert.doesNotMatch(tools, /CHAT_CARD_CLASS/)
  assert.match(runtime, /toolName === 'elicitation-form'/)
  assert.doesNotMatch(tools, /Questionnaire|MessageDraft|<Plan/)
  assert.doesNotMatch(runtime, /toolName === 'approval-card'/)
  assert.match(runtime, /onRespondToToolApproval/)
  assert.match(runtime, /问答卡片回复/)
  assert.match(tools, /Fallback: \(\) => null/)
  const toolUiDirectory = resolve(here, '../components/tool-ui')
  assert.deepEqual(sourceFiles(toolUiDirectory).map((path) => (
    path.slice(toolUiDirectory.length + 1).replaceAll('\\', '/')
  )).sort(), [
    'stats-display/_adapter.tsx',
    'stats-display/index.tsx',
    'stats-display/schema.ts',
    'stats-display/sparkline.tsx',
    'stats-display/stats-display.tsx',
  ])
  assert.equal(existsSync(resolve(here, '../components/tool-fallback.aui.tsx')), false)
})

test('chat keeps assistant-ui Viewport as its only scroll container', () => {
  const thread = read('../features/chat/components/ConversationThread.tsx')
  const globals = read('../styles/globals.css')
  assert.match(thread, /data-chat-viewport className="[^"]*overflow-y-auto[^"]*\[scrollbar-gutter:stable\][^"]*"/)
  assert.match(thread, /<\/ThreadPrimitive\.Viewport>\s*\{!readOnly && <div[^>]*data-chat-composer-bar>/)
  assert.doesNotMatch(thread, /ThreadPrimitive\.ViewportFooter/)
  assert.doesNotMatch(thread, /ScrollAreaPrimitive|<ScrollBar/)
  assert.doesNotMatch(globals, /data-radix-scroll-area-content/)
})

test('Agent OS uses native assistant-ui chunks through one live WebSocket bridge', () => {
  const controlPlane = read('../../server/src/agent-os/control-plane.ts')
  const agentService = read('../../server/src/agent-os/service.ts')
  const webhook = read('../../server/src/im/webhook-facade.ts')
  const webSocket = read('../../server/src/ws.ts')
  const transport = read('../features/chat/runtime/transport.ts')
  assert.match(controlPlane, /publish\(CH_ASSISTANT_STREAM/)
  assert.match(controlPlane, /kind === 'model\.delta'/)
  assert.match(controlPlane, /type: 'part-start'/)
  assert.match(controlPlane, /type: 'text-delta'/)
  assert.match(controlPlane, /event\.kind === 'tool\.started'/)
  assert.match(controlPlane, /toolName: data\.name/)
  assert.doesNotMatch(controlPlane, /toolName: 'ipython'/)
  assert.match(controlPlane, /event\.kind === 'knowledge\.rag\.completed'/)
  assert.doesNotMatch(controlPlane, /\/knowledge-preview/)
  assert.match(controlPlane, /delete ledgerData\.previewClaims/)
  assert.match(controlPlane, /delete ledgerData\.previewReferences/)
  assert.match(controlPlane, /toolName: 'cite_claims'/)
  assert.match(controlPlane, /toolName: 'read_document'/)
  assert.match(controlPlane, /type: 'tool-call-args-text-finish'/)
  assert.match(controlPlane, /type: 'result'/)
  assert.match(controlPlane, /type: 'message-finish'/)
  assert.match(agentService, /runtime\.runWork\(work\)\.catch/)
  assert.match(webhook, /publish\(CH_ASSISTANT_STREAM/)
  assert.match(webSocket, /sub\.subscribe\([\s\S]*CH_ASSISTANT_STREAM/)
  assert.match(transport, /event\.type === 'assistant\.stream'/)
  assert.match(transport, /applyAssistantStreamChunks/)
  assert.match(transport, /current\.id === `preview-\$\{metadata\.runId\}`/)
  assert.match(transport, /currentMetadata\.messageKind === 'text'/)
  assert.doesNotMatch(transport, /Rejected unstreamed assistant message/)
  assert.doesNotMatch(transport, /message\.delta|stream\.open/)
  assert.equal(existsSync(resolve(here, '../../server/src/messages/stream-reply.ts')), false)
})

test('legacy chat protocol and handwritten chat surfaces are absent', () => {
  for (const path of [
    '../im/assistantMessage.ts', '../im/assistantRuntime.tsx', '../im/MessageList.tsx',
    '../features/chat/state/messages.ts', '../features/chat/components/ChatComposer.tsx',
    '../components/messages/LingxiImMessage.tsx', '../components/messages/ImBubble.tsx',
    '../components/ui/message.tsx',
  ]) assert.equal(existsSync(resolve(here, path)), false, `${path} must be deleted`)
  const production = sourceFiles(srcRoot)
    .filter((path) => !path.endsWith('.test.ts') && !path.endsWith('.test.tsx'))
    .map((path) => readFileSync(path, 'utf8'))
    .join('\n')
  assert.doesNotMatch(production, /useMessages|createLingxiAssistantMessage|lingxi\.im\.message\.v1|legacy fallback/i)
})

test('only the chat transport boundary imports WuKong', () => {
  const offenders = sourceFiles(srcRoot)
    .filter((path) => !path.endsWith('.test.ts') && !path.endsWith('.test.tsx'))
    .filter((path) => !path.endsWith('lib\\im\\wukong.ts') && !path.endsWith('lib/im/wukong.ts'))
    .filter((path) => /from ['"]@\/lib\/im\/wukong['"]/.test(readFileSync(path, 'utf8')))
    .map((path) => path.slice(srcRoot.length).replaceAll('\\', '/'))
  assert.deepEqual(offenders, [
    '/features/chat/runtime/converter.ts',
    '/features/chat/runtime/transport.ts',
  ])
})

test('ChatPane remains a small shell and does not alter sidebar or header ownership', () => {
  const pane = read('../desktop/ChatPane.tsx')
  assert.ok(pane.length < 6_000)
  assert.match(pane, /<ConversationHeader/)
  assert.match(pane, /<ConversationThread/)
  assert.doesNotMatch(pane, /useExternalStoreRuntime|lingxiIm|MessagePrimitive|ComposerPrimitive/)
})

test('desktop shell surfaces use their canonical theme tokens', () => {
  const desktop = read('../desktop/DesktopApp.tsx')
  const rail = read('../desktop/WorkspaceRail.tsx')
  const conversations = read('../features/conversations/components/ConversationsPane.tsx')
  const header = read('../im/ConversationHeader.tsx')
  const profile = read('../im/Profile.tsx')
  const styles = read('../styles/globals.css')

  assert.match(rail, /server-rail[^"]*bg-\[var\(--workspace-chrome-surface\)\]/)
  assert.match(conversations, /SidebarFooter[^\n]*bg-sidebar/)
  assert.match(conversations, /im-conversations-sidebar[^"]*bg-sidebar text-sidebar-foreground/)
  assert.match(header, /im-conversation-header[^']*bg-sidebar text-sidebar-foreground/)
  assert.match(profile, /im-profile[^"]*bg-panel/)
  assert.match(styles, /--im-nav-surface: var\(--sidebar\)/)
  assert.match(styles, /--im-detail-surface: var\(--card\)/)
  assert.match(styles, /--workspace-chrome-surface: color-mix\(in oklch, var\(--background\) 96%, var\(--foreground\)\)/)
  assert.match(desktop, /desktop-openmaus[^"]*bg-\[var\(--workspace-chrome-surface\)\]/)
  assert.match(desktop, /rounded-2xl bg-background text-foreground/)
  assert.match(desktop, /id="desktop-conversation-layout"/)
  assert.match(desktop, /id="conversation-workspace"[^>]*>[\s\S]*id="desktop-conversation-content-layout"[\s\S]*id="conversation"[\s\S]*\{contextOpen &&/)
  assert.match(desktop, /CONTEXT_COLUMN_DEFAULT = 340/)
  assert.match(desktop, /id="context" defaultSize=\{CONTEXT_COLUMN_DEFAULT\}[^\n]*groupResizeBehavior="preserve-pixel-size"/)
})
